---
Name: coloredvariations
After: shop/*
---
Product:
  extensions:
    - ColoredProductExtension

ProductVariation:
  extensions:
    - ColoredProductVariationExtension

ProductCatalogAdmin:
  extensions:
    - ColoredProductAttributeAdmin
