---
Name: silvershopcoloredvariations
---
SilverShop\Pages\Product:
  extensions:
    - SilverShop\ColoredVariations\ColoredProductExtension

SilverShop\Admin\ProductCatalogAdmin:
  extensions:
    - SilverShop\ColoredVariations\ColoredProductAttributeAdmin
