---
Name: silvershopcoloredvariations
---
SilverShop\Page\Product:
  extensions:
    - SilverShop\ColoredVariations\ColoredProductExtension

SilverShop\Admin\ProductCatalogAdmin:
  extensions:
    - SilverShop\ColoredVariations\ColoredProductAttributeAdmin
